# Derived from: https://github.com/dnaka91/advent-of-code/blob/main/.github/workflows/docs.yml
name: github-pages-docs

on:
  push:
    branches:
      - '**'
      - '!gh-pages'
      - '!mutex_gh_pages'

env:
  CARGO_TERM_COLOR: always

jobs:
  doc_deploy:
    permissions:
      pages: write
      id-token: write
      contents: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: Swatinem/rust-cache@v2

      - name: Build docs
        run: nix develop ./#noFHS --command cargo doc --features logging,graphing

      - name: Add redirect
        run: echo '<meta http-equiv="refresh" content="0;url=sw8s_rust_lib/index.html">' > target/doc/index.html
      - name: Remove lock file
        run: rm target/doc/.lock

      - uses: ben-z/gh-action-mutex@v1.0-alpha-8
        with:
          branch: gh-pages-mutex

      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/doc 
          target-folder: docs/${{ github.ref_name }}
