name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install system requirements
      run:  |
        sudo apt-get update
        sudo apt-get install -y aptitude
        sudo aptitude install -y libgstreamer1.0-dev
        sudo apt-get install -y  llvm \
                                 libclang-dev \
                                 libopencv-dev \

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
