name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update Ubuntu Packages
      run: sudo apt-get update

    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: llvm \
          clang \
          libclang-dev \
          libopencv-dev \
          libavutil-dev \
          libavcodec-dev \
          libavformat-dev

    - name: Install gstreamer
      run: |
        sudo apt update
        sudo apt install -y aptitude
        sudo aptitude install -y libgstreamer1.0-dev

    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: cargo test --all-features --verbose
